import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Aperture,
  Apple,
  Archive,
  Atom,
  Award,
  Axe,
  Baby,
  Backpack,
  Banana,
  Barcode,
  Bath,
  Battery,
  BatteryCharging,
  Bean,
  Bed,
  Beer,
  Bell,
  Bike,
  Bird,
  Bluetooth,
  Bomb,
  Bone,
  Book,
  BookA,
  BookAudio,
  BookCheck,
  BookCopy,
  BookHeart,
  BookImage,
  BookMarked,
  Bookmark,
  BookOpen,
  BookOpenText,
  BookText,
  BoomBox,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  Calendar,
  Camera,
  CandlestickChart,
  Car,
  Carrot,
  Cat,
  Cherry,
  Church,
  CircleDot,
  Citrus,
  Clapperboard,
  Clock,
  Cloud,
  CloudSun,
  Clover,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dice1,
  Disc,
  Disc3,
  DiscAlbum,
  Dog,
  Donut,
  Drama,
  Drill,
  Drum,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  EyeOff,
  Fan,
  Feather,
  Fence,
  FileAudio,
  FileText,
  FileVideo,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Flower,
  Flower2,
  Focus,
  Folder,
  FolderHeart,
  FolderOpen,
  FolderTree,
  Footprints,
  Forklift,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Globe2,
  GraduationCap,
  Grape,
  Guitar,
  Ham,
  Hammer,
  HandHeart,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Home,
  Hop,
  Hotel,
  Hourglass,
  IceCreamCone,
  Image,
  Images,
  Inbox,
  Infinity as InfinityIcon,
  Key,
  KeyboardMusic,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  LibraryBig,
  Lightbulb,
  Link,
  ListMusic,
  ListVideo,
  Lock,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Milk,
  Monitor,
  MonitorPlay,
  Moon,
  MoonStar,
  Mountain,
  Mouse,
  Music,
  Music2,
  Music4,
  Navigation,
  Newspaper,
  Notebook,
  Nut,
  Palette,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  Phone,
  Piano,
  PiggyBank,
  Pin,
  Pizza,
  Plane,
  Play,
  Plug,
  Podcast,
  Popcorn,
  Projector,
  Puzzle,
  Rabbit,
  Radio,
  RadioTower,
  Rainbow,
  Rocket,
  Rss,
  Ruler,
  Sailboat,
  Sandwich,
  Scale,
  School,
  Scissors,
  Scroll,
  ScrollText,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Skull,
  Smile,
  Snowflake,
  Sofa,
  Sparkle,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Stars,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Syringe,
  Tablet,
  Tag,
  Target,
  Telescope,
  TentTree,
  Terminal,
  Theater,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Tv2,
  Umbrella,
  University,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Videotape,
  Volume2,
  Wand,
  WandSparkles,
  Watch,
  Waves,
  Webcam,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

/** Convert PascalCase to kebab-case */
export function pascalToKebab(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/** Convert kebab-case to PascalCase */
export function kebabToPascal(str: string): string {
  return str.replace(/(^|-)([a-z])/g, (_, __, c: string) => c.toUpperCase());
}

// ─── Catalog: [kebabName, Component, ...searchKeywords] ───
const RAW: [string, LucideIcon, string[]][] = [
  // ── Media / Video ──
  ["film", Film, ["电影", "movie", "film", "影片"]],
  ["tv", Tv, ["电视", "tv", "television"]],
  ["tv-2", Tv2, ["电视", "tv", "显示器"]],
  ["video", Video, ["视频", "video", "录像"]],
  ["videotape", Videotape, ["录像带", "videotape", "磁带"]],
  ["clapperboard", Clapperboard, ["场记板", "clapperboard", "拍摄"]],
  ["projector", Projector, ["投影仪", "projector", "放映"]],
  ["monitor-play", MonitorPlay, ["播放", "monitor", "屏幕"]],
  ["play", Play, ["播放", "play", "开始"]],
  ["theater", Theater, ["剧院", "theater", "影院"]],
  ["list-video", ListVideo, ["视频列表", "playlist", "video"]],
  ["file-video", FileVideo, ["视频文件", "file", "video"]],
  ["drama", Drama, ["戏剧", "drama", "表演"]],

  // ── Music / Audio ──
  ["music", Music, ["音乐", "music", "歌曲"]],
  ["music-2", Music2, ["音乐", "music", "音符"]],
  ["music-4", Music4, ["音乐", "music", "曲"]],
  ["list-music", ListMusic, ["歌单", "playlist", "music"]],
  ["headphones", Headphones, ["耳机", "headphones", "音频"]],
  ["mic", Mic, ["麦克风", "mic", "录音"]],
  ["radio", Radio, ["收音机", "radio", "广播"]],
  ["radio-tower", RadioTower, ["电台", "radio", "tower", "信号塔"]],
  ["podcast", Podcast, ["播客", "podcast", "节目"]],
  ["speaker", Speaker, ["扬声器", "speaker", "音响"]],
  ["volume-2", Volume2, ["音量", "volume", "声音"]],
  ["disc", Disc, ["唱片", "disc", "光盘"]],
  ["disc-3", Disc3, ["唱片", "disc", "cd"]],
  ["disc-album", DiscAlbum, ["专辑", "album", "唱片"]],
  ["guitar", Guitar, ["吉他", "guitar", "乐器"]],
  ["piano", Piano, ["钢琴", "piano", "键盘"]],
  ["drum", Drum, ["鼓", "drum", "打击乐"]],
  ["keyboard-music", KeyboardMusic, ["键盘", "keyboard", "音乐"]],
  ["boom-box", BoomBox, ["音箱", "boombox", "收音机"]],
  ["file-audio", FileAudio, ["音频文件", "audio", "file"]],

  // ── Camera / Image ──
  ["camera", Camera, ["相机", "camera", "拍照"]],
  ["image", Image, ["图片", "image", "照片"]],
  ["images", Images, ["图集", "images", "相册"]],
  ["focus", Focus, ["对焦", "focus", "聚焦"]],
  ["aperture", Aperture, ["光圈", "aperture", "镜头"]],
  ["webcam", Webcam, ["摄像头", "webcam", "直播"]],
  ["eye", Eye, ["眼睛", "eye", "查看"]],
  ["eye-off", EyeOff, ["隐藏", "eye", "off", "不可见"]],

  // ── Books / Reading ──
  ["book-open", BookOpen, ["书", "book", "阅读", "open"]],
  ["book-open-text", BookOpenText, ["书", "book", "文本", "阅读"]],
  ["book-text", BookText, ["书", "book", "text", "文字"]],
  ["book-marked", BookMarked, ["书签", "bookmark", "标记"]],
  ["book-copy", BookCopy, ["复制", "book", "copy"]],
  ["book-check", BookCheck, ["已读", "book", "check"]],
  ["book-heart", BookHeart, ["收藏", "book", "heart", "喜欢"]],
  ["book-image", BookImage, ["图书", "book", "image", "画册"]],
  ["book-audio", BookAudio, ["有声书", "audiobook", "book"]],
  ["book-a", BookA, ["书", "book", "文学"]],
  ["book", Book, ["书", "book", "图书"]],
  ["library", Library, ["图书馆", "library", "书架"]],
  ["library-big", LibraryBig, ["图书馆", "library", "大书架"]],
  ["scroll", Scroll, ["卷轴", "scroll", "文献"]],
  ["scroll-text", ScrollText, ["文献", "scroll", "text"]],
  ["notebook", Notebook, ["笔记本", "notebook", "记录"]],
  ["newspaper", Newspaper, ["报纸", "newspaper", "新闻"]],
  ["rss", Rss, ["订阅", "rss", "feed"]],
  ["file-text", FileText, ["文档", "file", "text", "文件"]],

  // ── Files / Folders ──
  ["folder", Folder, ["文件夹", "folder", "目录"]],
  ["folder-open", FolderOpen, ["打开文件夹", "folder", "open"]],
  ["folder-tree", FolderTree, ["文件树", "folder", "tree", "目录"]],
  ["folder-heart", FolderHeart, ["收藏夹", "folder", "heart"]],
  ["archive", Archive, ["归档", "archive", "压缩"]],
  ["inbox", Inbox, ["收件箱", "inbox", "邮件"]],
  ["layers", Layers, ["图层", "layers", "堆叠"]],
  ["box", Box, ["盒子", "box", "容器"]],

  // ── Nature / Weather ──
  ["sun", Sun, ["太阳", "sun", "日"]],
  ["sunrise", Sunrise, ["日出", "sunrise", "清晨"]],
  ["sunset", Sunset, ["日落", "sunset", "黄昏"]],
  ["moon", Moon, ["月亮", "moon", "夜"]],
  ["moon-star", MoonStar, ["星月", "moon", "star", "夜晚"]],
  ["cloud", Cloud, ["云", "cloud", "天空"]],
  ["cloud-sun", CloudSun, ["多云", "cloud", "sun", "晴转多云"]],
  ["snowflake", Snowflake, ["雪花", "snow", "冬天"]],
  ["rainbow", Rainbow, ["彩虹", "rainbow", "七彩"]],
  ["leaf", Leaf, ["叶子", "leaf", "自然"]],
  ["tree-pine", TreePine, ["松树", "tree", "pine", "森林"]],
  ["sprout", Sprout, ["嫩芽", "sprout", "生长"]],
  ["flower", Flower, ["花", "flower", "植物"]],
  ["flower-2", Flower2, ["花", "flower", "植物"]],
  ["clover", Clover, ["三叶草", "clover", "幸运"]],
  ["mountain", Mountain, ["山", "mountain", "户外"]],
  ["waves", Waves, ["海浪", "waves", "水", "海洋"]],
  ["wind", Wind, ["风", "wind", "空气"]],
  ["umbrella", Umbrella, ["雨伞", "umbrella", "rain"]],
  ["flame", Flame, ["火焰", "flame", "火"]],

  // ── Shapes / Abstract ──
  ["circle-dot", CircleDot, ["圆点", "circle", "dot"]],
  ["hexagon", Hexagon, ["六边形", "hexagon", "形状"]],
  ["diamond", Diamond, ["钻石", "diamond", "菱形"]],
  ["star", Star, ["星星", "star", "收藏"]],
  ["stars", Stars, ["星星", "stars", "闪烁"]],
  ["heart", Heart, ["心", "heart", "爱"]],
  ["heart-pulse", HeartPulse, ["心跳", "heart", "pulse", "生命"]],
  ["sparkle", Sparkle, ["闪光", "sparkle", "光芒"]],
  ["sparkles", Sparkles, ["闪烁", "sparkles", "魔法"]],
  ["wand-sparkles", WandSparkles, ["魔杖", "wand", "sparkles", "魔法"]],
  ["infinity", InfinityIcon, ["无限", "infinity", "永恒"]],
  ["atom", Atom, ["原子", "atom", "科学"]],

  // ── People / Animals ──
  ["user", User, ["用户", "user", "人"]],
  ["users", Users, ["用户组", "users", "团队"]],
  ["baby", Baby, ["婴儿", "baby", "儿童"]],
  ["smile", Smile, ["笑脸", "smile", "表情"]],
  ["thumbs-up", ThumbsUp, ["点赞", "thumbs", "up", "好"]],
  ["skull", Skull, ["骷髅", "skull", "恐怖"]],
  ["ghost", Ghost, ["幽灵", "ghost", "鬼"]],
  ["cat", Cat, ["猫", "cat", "宠物"]],
  ["dog", Dog, ["狗", "dog", "宠物"]],
  ["bird", Bird, ["鸟", "bird", "飞"]],
  ["fish", Fish, ["鱼", "fish", "水"]],
  ["rabbit", Rabbit, ["兔子", "rabbit", "宠物"]],
  ["bug", Bug, ["虫子", "bug", "昆虫"]],
  ["paw-print", PawPrint, ["爪印", "paw", "宠物"]],

  // ── Food / Drink ──
  ["coffee", Coffee, ["咖啡", "coffee", "饮品"]],
  ["wine", Wine, ["酒", "wine", "红酒"]],
  ["beer", Beer, ["啤酒", "beer", "饮料"]],
  ["milk", Milk, ["牛奶", "milk", "饮品"]],
  ["cup-soda", CupSoda, ["杯子", "cup", "茶"]],
  ["pizza", Pizza, ["披萨", "pizza", "食物"]],
  ["sandwich", Sandwich, ["三明治", "sandwich", "食物"]],
  ["cake", Cake, ["蛋糕", "cake", "甜点"]],
  ["cookie", Cookie, ["饼干", "cookie", "零食"]],
  ["donut", Donut, ["甜甜圈", "donut", "甜点"]],
  ["apple", Apple, ["苹果", "apple", "水果"]],
  ["cherry", Cherry, ["樱桃", "cherry", "水果"]],
  ["grape", Grape, ["葡萄", "grape", "水果"]],
  ["banana", Banana, ["香蕉", "banana", "水果"]],
  ["carrot", Carrot, ["胡萝卜", "carrot", "蔬菜"]],
  ["egg", Egg, ["鸡蛋", "egg", "食物"]],
  ["croissant", Croissant, ["牛角包", "croissant", "面包"]],
  ["popcorn", Popcorn, ["爆米花", "popcorn", "零食"]],
  ["utensils", Utensils, ["餐具", "utensils", "厨房"]],
  ["ham", Ham, ["火腿", "ham", "肉"]],
  ["wheat", Wheat, ["麦穗", "wheat", "粮食"]],
  ["bean", Bean, ["豆子", "bean", "食物"]],
  ["citrus", Citrus, ["柑橘", "citrus", "水果"]],
  ["hop", Hop, ["啤酒花", "hop", "酿造"]],
  ["ice-cream-cone", IceCreamCone, ["冰淇淋", "ice cream", "甜品"]],
  ["nut", Nut, ["坚果", "nut", "零食"]],

  // ── Objects / Tools ──
  ["gift", Gift, ["礼物", "gift", "送"]],
  ["crown", Crown, ["皇冠", "crown", "王"]],
  ["trophy", Trophy, ["奖杯", "trophy", "胜利"]],
  ["medal", Medal, ["奖牌", "medal", "荣誉"]],
  ["award", Award, ["奖项", "award", "荣誉"]],
  ["target", Target, ["靶子", "target", "目标"]],
  ["flag", Flag, ["旗帜", "flag", "标志"]],
  ["bookmark", Bookmark, ["书签", "bookmark", "收藏"]],
  ["tag", Tag, ["标签", "tag", "分类"]],
  ["lightbulb", Lightbulb, ["灯泡", "lightbulb", "想法"]],
  ["lamp", Lamp, ["台灯", "lamp", "照明"]],
  ["palette", Palette, ["调色板", "palette", "颜色", "绘画"]],
  ["brush", Brush, ["画笔", "brush", "绘画"]],
  ["pen", Pen, ["笔", "pen", "写"]],
  ["pencil", Pencil, ["铅笔", "pencil", "写"]],
  ["ruler", Ruler, ["尺子", "ruler", "测量"]],
  ["scissors", Scissors, ["剪刀", "scissors", "剪切"]],
  ["key", Key, ["钥匙", "key", "安全"]],
  ["lock", Lock, ["锁", "lock", "安全"]],
  ["shield", Shield, ["盾牌", "shield", "防护"]],
  ["shield-check", ShieldCheck, ["安全", "shield", "check", "验证"]],
  ["wrench", Wrench, ["扳手", "wrench", "工具"]],
  ["hammer", Hammer, ["锤子", "hammer", "工具"]],
  ["compass", Compass, ["指南针", "compass", "方向"]],
  ["map", MapIcon, ["地图", "map", "导航"]],
  ["map-pin", MapPin, ["定位", "map", "pin", "位置"]],
  ["anchor", Anchor, ["锚", "anchor", "港口"]],
  ["rocket", Rocket, ["火箭", "rocket", "发射"]],
  ["zap", Zap, ["闪电", "zap", "电"]],
  ["bell", Bell, ["铃铛", "bell", "通知"]],
  ["clock", Clock, ["时钟", "clock", "时间"]],
  ["timer", Timer, ["计时器", "timer", "倒计时"]],
  ["hourglass", Hourglass, ["沙漏", "hourglass", "时间"]],
  ["calendar", Calendar, ["日历", "calendar", "日期"]],
  ["scale", Scale, ["天平", "scale", "衡量"]],
  ["magnet", Magnet, ["磁铁", "magnet", "吸引"]],
  ["fingerprint", Fingerprint, ["指纹", "fingerprint", "身份"]],
  ["flashlight", Flashlight, ["手电筒", "flashlight", "照亮"]],
  ["glasses", Glasses, ["眼镜", "glasses", "视力"]],
  ["watch", Watch, ["手表", "watch", "时间"]],
  ["barcode", Barcode, ["条码", "barcode", "扫描"]],
  ["puzzle", Puzzle, ["拼图", "puzzle", "益智"]],
  ["wand", Wand, ["魔杖", "wand", "魔法"]],
  ["sword", Sword, ["剑", "sword", "武器"]],
  ["axe", Axe, ["斧头", "axe", "工具"]],
  ["bomb", Bomb, ["炸弹", "bomb", "爆炸"]],
  ["bone", Bone, ["骨头", "bone", "宠物"]],

  // ── Buildings / Places ──
  ["home", Home, ["家", "home", "房子"]],
  ["building", Building, ["建筑", "building", "大楼"]],
  ["building-2", Building2, ["办公楼", "building", "城市"]],
  ["store", Store, ["商店", "store", "购物"]],
  ["hotel", Hotel, ["酒店", "hotel", "住宿"]],
  ["school", School, ["学校", "school", "教育"]],
  ["university", University, ["大学", "university", "教育"]],
  ["church", Church, ["教堂", "church", "宗教"]],
  ["landmark", Landmark, ["地标", "landmark", "名胜"]],
  ["tent-tree", TentTree, ["露营", "tent", "tree", "户外"]],
  ["fence", Fence, ["栅栏", "fence", "围栏"]],

  // ── Tech / Digital ──
  ["monitor", Monitor, ["显示器", "monitor", "屏幕"]],
  ["laptop", Laptop, ["笔记本", "laptop", "电脑"]],
  ["tablet", Tablet, ["平板", "tablet", "ipad"]],
  ["cpu", Cpu, ["处理器", "cpu", "芯片"]],
  ["server", Server, ["服务器", "server", "机房"]],
  ["database", Database, ["数据库", "database", "存储"]],
  ["hard-drive", HardDrive, ["硬盘", "hard drive", "存储"]],
  ["globe", Globe, ["地球", "globe", "网络"]],
  ["globe-2", Globe2, ["地球", "globe", "世界"]],
  ["wifi", Wifi, ["无线", "wifi", "网络"]],
  ["bluetooth", Bluetooth, ["蓝牙", "bluetooth", "连接"]],
  ["link", Link, ["链接", "link", "连接"]],
  ["code", Code, ["代码", "code", "编程"]],
  ["terminal", Terminal, ["终端", "terminal", "命令行"]],
  ["settings", Settings, ["设置", "settings", "配置"]],
  ["cog", Cog, ["齿轮", "cog", "设置"]],
  ["search", Search, ["搜索", "search", "查找"]],
  ["upload", Upload, ["上传", "upload", "发送"]],
  ["plug", Plug, ["插头", "plug", "电源"]],
  ["battery", Battery, ["电池", "battery", "电量"]],
  ["battery-charging", BatteryCharging, ["充电", "battery", "charging"]],
  ["mouse", Mouse, ["鼠标", "mouse", "点击"]],

  // ── Transport ──
  ["car", Car, ["汽车", "car", "驾驶"]],
  ["bus", Bus, ["公交", "bus", "巴士"]],
  ["train", Train, ["火车", "train", "铁路"]],
  ["plane", Plane, ["飞机", "plane", "航空"]],
  ["ship", Ship, ["轮船", "ship", "航海"]],
  ["sailboat", Sailboat, ["帆船", "sailboat", "航行"]],
  ["bike", Bike, ["自行车", "bike", "骑行"]],
  ["truck", Truck, ["卡车", "truck", "货车"]],
  ["ticket", Ticket, ["票", "ticket", "入场"]],
  ["navigation", Navigation, ["导航", "navigation", "方向"]],

  // ── Communication ──
  ["mail", Mail, ["邮件", "mail", "信"]],
  ["message-circle", MessageCircle, ["消息", "message", "聊天"]],
  ["phone", Phone, ["电话", "phone", "通话"]],
  ["megaphone", Megaphone, ["喇叭", "megaphone", "广播"]],
  ["hand-heart", HandHeart, ["关爱", "hand", "heart", "志愿"]],

  // ── Commerce / Finance ──
  ["shopping-cart", ShoppingCart, ["购物车", "shopping", "cart"]],
  ["shopping-bag", ShoppingBag, ["购物袋", "shopping", "bag"]],
  ["credit-card", CreditCard, ["信用卡", "credit", "card", "支付"]],
  ["coins", Coins, ["硬币", "coins", "金钱"]],
  ["piggy-bank", PiggyBank, ["存钱罐", "piggy bank", "储蓄"]],
  ["briefcase", Briefcase, ["公文包", "briefcase", "工作"]],

  // ── Sports / Activity ──
  ["dumbbell", Dumbbell, ["哑铃", "dumbbell", "健身"]],
  ["gamepad-2", Gamepad2, ["游戏手柄", "gamepad", "游戏"]],
  ["telescope", Telescope, ["望远镜", "telescope", "观测"]],
  ["microscope", Microscope, ["显微镜", "microscope", "科学"]],
  ["flask-conical", FlaskConical, ["烧瓶", "flask", "实验"]],
  ["brain", Brain, ["大脑", "brain", "智力"]],
  ["stethoscope", Stethoscope, ["听诊器", "stethoscope", "医疗"]],
  ["syringe", Syringe, ["注射器", "syringe", "医疗"]],
  ["graduation-cap", GraduationCap, ["学士帽", "graduation", "毕业", "教育"]],
  ["languages", Languages, ["语言", "languages", "翻译"]],
  ["gem", Gem, ["宝石", "gem", "珠宝"]],
  ["party-popper", PartyPopper, ["派对", "party", "庆祝"]],

  // ── Lifestyle ──
  ["shirt", Shirt, ["衬衫", "shirt", "服装"]],
  ["sofa", Sofa, ["沙发", "sofa", "家具"]],
  ["bed", Bed, ["床", "bed", "睡觉"]],
  ["bath", Bath, ["浴缸", "bath", "洗澡"]],
  ["fan", Fan, ["风扇", "fan", "电器"]],
  ["ear", Ear, ["耳朵", "ear", "听"]],
  ["backpack", Backpack, ["背包", "backpack", "旅行"]],
  ["paperclip", Paperclip, ["回形针", "paperclip", "附件"]],
  ["pin", Pin, ["图钉", "pin", "固定"]],
  ["footprints", Footprints, ["脚印", "footprints", "足迹"]],
  ["feather", Feather, ["羽毛", "feather", "轻"]],
  ["candlestick-chart", CandlestickChart, ["K线", "chart", "股票"]],
  ["gauge", Gauge, ["仪表盘", "gauge", "速度"]],

  // ── Construction / Industry ──
  ["construction", Construction, ["施工", "construction", "建设"]],
  ["drill", Drill, ["电钻", "drill", "工具"]],
  ["shovel", Shovel, ["铲子", "shovel", "挖"]],
  ["forklift", Forklift, ["叉车", "forklift", "搬运"]],
  ["cable", Cable, ["电缆", "cable", "线"]],
  ["calculator", Calculator, ["计算器", "calculator", "计算"]],
  ["dice-1", Dice1, ["骰子", "dice", "随机"]],
];

export interface IconCatalogEntry {
  /** kebab-case name, e.g. "book-open" */
  name: string;
  component: LucideIcon;
  keywords: string[];
}

export const ICON_CATALOG: IconCatalogEntry[] = RAW.map(
  ([name, component, keywords]) => ({
    name,
    component,
    keywords,
  }),
);

/** Lookup map: kebab-case name → LucideIcon component */
export const ICON_COMPONENT_MAP = new Map<string, LucideIcon>(
  ICON_CATALOG.map((e) => [e.name, e.component]),
);
