/**
 * Tokimo design tokens — kebab-case CSS variable names exposed as
 * a typed object. Use `cssVar(TOKEN.accent)` to produce a runtime
 * `var(--color-accent)` expression for inline styles or string
 * concatenation where Tailwind utilities aren't viable.
 *
 * Source of truth: packages/ui/src/theme.css.
 * Generated by hand — keep in sync when adding/removing tokens.
 */

export const TOKEN = {
  // Surfaces
  surfaceBase: "--color-surface-base",
  surfaceRaised: "--color-surface-raised",
  surfaceOverlay: "--color-surface-overlay",
  surfaceOverlayHover: "--color-surface-overlay-hover",
  surfaceSunken: "--color-surface-sunken",
  surfaceSidebar: "--color-surface-sidebar",
  surfaceContent: "--color-surface-content",
  surfaceInverted: "--color-surface-inverted",

  // Foreground
  fgPrimary: "--color-fg-primary",
  fgSecondary: "--color-fg-secondary",
  fgMuted: "--color-fg-muted",
  fgDisabled: "--color-fg-disabled",
  fgOnRaised: "--color-fg-on-raised",
  fgOnOverlay: "--color-fg-on-overlay",
  fgOnInverted: "--color-fg-on-inverted",
  fgOnAccent: "--color-fg-on-accent",

  // Borders
  borderSubtle: "--color-border-subtle",
  borderBase: "--color-border-base",
  borderStrong: "--color-border-strong",
  borderAccent: "--color-border-accent",

  // Fills
  fillTertiary: "--color-fill-tertiary",
  fillSecondary: "--color-fill-secondary",
  fillPrimary: "--color-fill-primary",
  fillSkeleton: "--color-fill-skeleton",

  // Accent
  accent: "--color-accent",
  accentHover: "--color-accent-hover",
  accentActive: "--color-accent-active",
  accentSubtle: "--color-accent-subtle",
  accentSubtleHover: "--color-accent-subtle-hover",
  accentMuted: "--color-accent-muted",
  accentText: "--color-accent-text",
  accentContrast: "--color-accent-contrast",
  accentSecondary: "--color-accent-secondary",
  accentSecondaryText: "--color-accent-secondary-text",

  // State
  stateSuccessBase: "--color-state-success-base",
  stateSuccessSubtle: "--color-state-success-subtle",
  stateSuccessText: "--color-state-success-text",
  stateWarningBase: "--color-state-warning-base",
  stateWarningSubtle: "--color-state-warning-subtle",
  stateWarningText: "--color-state-warning-text",
  stateDangerBase: "--color-state-danger-base",
  stateDangerSubtle: "--color-state-danger-subtle",
  stateDangerText: "--color-state-danger-text",
  stateInfoBase: "--color-state-info-base",
  stateInfoSubtle: "--color-state-info-subtle",
  stateInfoText: "--color-state-info-text",

  // Window / glass
  windowBlur: "--window-blur",
  windowOpacity: "--window-opacity",
  windowRadius: "--window-radius",
  glassBlur: "--glass-blur",
  glassSaturate: "--glass-saturate",
  overlayBlur: "--overlay-blur",
  headerBg: "--header-bg",
  surfaceOverlayRgb: "--color-surface-overlay-rgb",

  // Layout calculation vars (set programmatically, not theme constants)
  submenuAvailH: "--submenu-avail-h",

  // Decorative
  aurora1: "--aurora-1",
  aurora2: "--aurora-2",
  aurora3: "--aurora-3",
  auroraOpacity: "--aurora-opacity",
  gradientFrom: "--gradient-from",
  gradientTo: "--gradient-to",
  cardTopLineOpacity: "--card-top-line-opacity",

  // Scrollbar
  scrollbarThumb: "--scrollbar-thumb",
  scrollbarThumbHover: "--scrollbar-thumb-hover",

  // Shadows
  shadowSm: "--shadow-sm",
  shadowMd: "--shadow-md",
  shadowLg: "--shadow-lg",
  shadowGlass: "--shadow-glass",

  // Motion
  motionDurationFast: "--motion-duration-fast",
  motionDurationNormal: "--motion-duration-normal",
  motionDurationSlow: "--motion-duration-slow",
  motionEaseIn: "--motion-ease-in",
  motionEaseOut: "--motion-ease-out",
  motionEaseInOut: "--motion-ease-in-out",

  // Radius
  radiusSm: "--radius-sm",
  radiusMd: "--radius-md",
  radiusLg: "--radius-lg",
  radiusXl: "--radius-xl",
  radiusPill: "--radius-pill",

  // Runtime component variables (set via React inline style, not theme.css)
  playerSubtitleColor: "--player-subtitle-color",
  playerSubtitleFontFamily: "--player-subtitle-font-family",
  playerSubtitleFontSize: "--player-subtitle-font-size",
  playerSubtitleBg: "--player-subtitle-bg",
  playerSubtitleWeight: "--player-subtitle-weight",
  playerSubtitleShadow: "--player-subtitle-shadow",
} as const;

export type TokenKey = keyof typeof TOKEN;
export type TokenName = (typeof TOKEN)[TokenKey];

/** Produce a `var(--token-name)` expression for inline styles. */
export const cssVar = (token: TokenName): string => `var(${token})`;
